### ISSUE TITLE
--filename without a cluster being configured

### ISSUE THREAD

**Issue by jleonar** [viglesiasce/kube-lint#3]
I might be misreading how you intend this to work but I am looking to validate the yaml files prior to deploying them to a cluster.  

However, when I run it with the following command:
kube-lint pods --filename ./pod.yaml --config ./config.yaml

I get an error (lookup: no such host) as it is trying to connect to a cluster I don't have running at the moment. 

Basically I want to use kube-lint as a preflight check of the yaml files prior to them every touching the cluster.  Therefore, kube-lint might be running on a build server that doesn't even have kubectl configured.

**Comment by viglesiasce** [comment]
Hey there! Thanks for filing this. I believe it should be fixed by #2. Can you make sure you have that commit?

How did you like the config syntax for rules? Flexible enough for what you were trying to do? Too cumbersome?

**Comment by jleonar** [comment]
Yep, I am not sure why my initial pull didn't include that. 

As for additional feedback, I am just getting to writing some of our rules but what we currently know, it looks like it will handle most scenarios.  I will provide additional feedback as we run into other issues.
